apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: testkube-tests
 namespace: argocd
spec:
 project: default
 source:
   repoURL: https://github.com/Saliha067/argocd.git
   targetRevision: HEAD
   path: postman-collections
   plugin:
     name: testkube
 destination:
   server: https://kubernetes.default.svc
   namespace: testkube
